### ISSUE TITLE
Can't publish catalog app

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#215]
I've updated and published the bridge, tried to update the catalog app as regular but it doesn't bundle. I've updated aurelia-bundler and node-js - it may have to do with these updates, but I'm not sure.

Symptoms:
- bundled files are generated in `./` and persist even after unbundling (not sure if that's expected)
- either `showdown` or `$` (jQuery) cannot be loaded, depending on what the bundler spits out - seems random

I will have to investigate this, because it could be a consecutive fault of an issue I had building the current bridge version (#211).

**Comment by Thanood** [comment]
After downgradting aurelia-bundler to `^0.2.11`, reinstalling `node_modules` as well as `jspm_packages` and downgrading jquery to `^2.2.0` bundling was possible again.

I will close this when deploy succeeded.

**Comment by Thanood** [comment]
Bundling fails again...

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:801:5)
    at exports.writeOutputs (C:\Users\Daniel\Documents\Entwicklung\js\aurelia\demo-materialize\node_modules\systemjs-builder\lib\output.js:145:23)
    at C:\Users\Daniel\Documents\Entwicklung\js\aurelia\demo-materialize\node_modules\systemjs-builder\lib\builder.js:373:14
    at lib$rsvp$$internal$$tryCatch (C:\Users\Daniel\Documents\Entwicklung\js\aurelia\demo-materialize\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Daniel\Documents\Entwicklung\js\aurelia\demo-materialize\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Daniel\Documents\Entwicklung\js\aurelia\demo-materialize\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Daniel\Documents\Entwicklung\js\aurelia\demo-materialize\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Thanood** [comment]
"fixed" this by myking this change to `node_modules\systemjs-builder\lib\output.js:145`:

```javascript
var fileName = outFile ? (path.basename(outFile) || 'output.js') : 'output.js';
```

**Comment by Thanood** [comment]
This time, publishing worked but bluebird isn't fount, although [it's there](https://github.com/aurelia-ui-toolkits/demo-materialize/tree/gh-pages/vendor)

**Comment by Thanood** [comment]
never happened again
