### ISSUE TITLE
n TypeError: _aureliaPal.PLATFORM.moduleName is not a function

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#474]
Hi I have a code base that works on one computer but another just gives this error in the browser. 

vendor-bundle.js:1399 Unhandled rejection TypeError: _aureliaPal.PLATFORM.moduleName is not a function
    at ConfigBuilder.useNavbar (http://localhost:9000/scripts/materialize-bundle.js:25796:54)
    at http://localhost:9000/scripts/app-bundle.js:1016:14
    at Object.configure (http://localhost:9000/node_modules/aurelia-materialize-bridge/dist/amd/index.js:29:7)
    at http://localhost:9000/scripts/vendor-bundle.js:32448:36
From previous event:

The commandline doesn't show any errors. I have updated aurelia-ci, npm and node with no luck

Any suggestions what could cause this on one machine ?

Thanks

**Comment by glennpierce** [comment]
Ok deleting my node_modules dir and doing npm install fixed this.
