### ISSUE TITLE
errors on build after adding bundle to aurelia.json

### ISSUE THREAD

**Issue by lukpep** [aurelia-ui-toolkits/aurelia-materialize-bridge#483]
aurelia-cli: 0.31.1
aurelia-materialize-bride: 0.31.0

when adding:
```
{
  "name": "materialize-bundle.js",
  "dependencies": [
    "jquery",
    {
      "name": "materialize-css",
      "path": "../node_modules/materialize-css/dist",
      "main": "js/materialize.amd",
      "deps": [
        "jquery"
      ],
      "resources": [
        "css/materialize.css"
      ],
      "exports": "Materialize"
    },
    {
      "name": "aurelia-materialize-bridge",
      "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
      "main": "index",
      "deps": [
        "jquery"
      ],
      "resources": [
        "**/*.{css,html}",
        "index.js"
      ]
    }
  ]
}
```

to aurelia.json I get errors on build:

> C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app>au build
> Starting 'readProjectConfiguration'...
> { uid: 1,
>   name: 'readProjectConfiguration',
>   branch: false,
>   error:
>    TypeError: Cannot read property 'indexOf' of undefined
>        at reverseEngineer (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\package-analyzer.js:22:26)
>        at analyzeDependency (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundler.js:204:26)
>        at configureDependency (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundler.js:129:12)
>        at Utils.runSequentially.dep (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundle.js:42:24)
>        at exec (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\utils.js:23:14),
>   duration: [ 0, 58376657 ],
>   time: 1506934664785 }
> { uid: 0,
>   name: '<series>',
>   branch: true,
>   error:
>    TypeError: Cannot read property 'indexOf' of undefined
>        at reverseEngineer (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\package-analyzer.js:22:26)
>        at analyzeDependency (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundler.js:204:26)
>        at configureDependency (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundler.js:129:12)
>        at Utils.runSequentially.dep (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundle.js:42:24)
>        at exec (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\utils.js:23:14),
>   duration: [ 0, 63842721 ],
>   time: 1506934664790 }
> TypeError: Cannot read property 'indexOf' of undefined
>     at reverseEngineer (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\package-analyzer.js:22:26)
>     at analyzeDependency (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundler.js:204:26)
>     at configureDependency (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundler.js:129:12)
>     at Utils.runSequentially.dep (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\bundle.js:42:24)
>     at exec (C:\Users\lukasz.peplinski\Documents\projects\GalCloud-web-app\node_modules\aurelia-cli\lib\build\utils.js:23:14)

all previous installation steps were fine.

**Comment by gen-failure** [comment]
I am experiencing the same issue

**Comment by Thanood** [comment]
Hi and sorry for the delay..

Since this happens at `readProjectConfiguration` this may as well be a JSON syntax error.
Would you mind posting your entire `aurelia.json` or at least the whole `bundles` part?

Last time I checked with this setup, it just worked..

For reference, here's mine:

```json
"bundles": [
      {
        "name": "app-bundle.js",
        "source": [
          "[**/*.js]",
          "**/*.{css,html}"
        ]
      },
      {
        "name": "vendor-bundle.js",
        "prepend": [
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "node_modules/aurelia-cli/lib/resources/scripts/configure-bluebird.js",
          "node_modules/requirejs/require.js"
        ],
        "dependencies": [
          "aurelia-binding",
          "aurelia-bootstrapper",
          "aurelia-dependency-injection",
          "aurelia-event-aggregator",
          "aurelia-framework",
          "aurelia-history",
          "aurelia-history-browser",
          "aurelia-loader",
          "aurelia-loader-default",
          "aurelia-logging",
          "aurelia-logging-console",
          "aurelia-metadata",
          "aurelia-pal",
          "aurelia-pal-browser",
          "aurelia-path",
          "aurelia-polyfills",
          "aurelia-route-recognizer",
          "aurelia-router",
          "aurelia-task-queue",
          "aurelia-templating",
          "aurelia-templating-binding",
          {
            "name": "aurelia-templating-resources",
            "path": "../node_modules/aurelia-templating-resources/dist/amd",
            "main": "aurelia-templating-resources"
          },
          {
            "name": "aurelia-templating-router",
            "path": "../node_modules/aurelia-templating-router/dist/amd",
            "main": "aurelia-templating-router"
          },
          {
            "name": "aurelia-testing",
            "path": "../node_modules/aurelia-testing/dist/amd",
            "main": "aurelia-testing",
            "env": "dev"
          },
          "text"
        ]
      },
      {
        "name": "materialize-bundle.js",
        "dependencies": [
          "jquery",
          {
            "name": "materialize-css",
            "path": "../node_modules/materialize-css/dist",
            "main": "js/materialize.amd",
            "deps": [
              "jquery"
            ],
            "resources": [
              "css/materialize.css"
            ],
            "exports": "Materialize"
          },
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery"
            ],
            "resources": [
              "**/*.{css,html}",
              "index.js"
            ]
          }
        ]
      }
    ]
```
